spring.application.name=connector-rag-poc

# Temporary local direct config (move to .env later)
spring.ai.openai.api-key=
spring.data.mongodb.uri=mongodb+srv://cip_user:VaKr8wHWlEL9YJUn@cluster0.ggbxo0v.mongodb.net/?appName=Cluster0
spring.ai.vectorstore.pinecone.api-key=pcsk_3DBsK9_KatqKDtm9jLj7U2oWriNbgrWopN3riyWm463cLZV46PDpwSFDLj7UdMD6hvHeiP
spring.ai.vectorstore.pinecone.environment=
spring.ai.vectorstore.pinecone.index-name=ai-assistant-index
spring.ai.vectorstore.pinecone.namespace=default
